# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-07 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_feature_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='price',
            field=models.IntegerField(default=5),
        ),
    ]
