# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-11 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20190811_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='price',
            field=models.IntegerField(default=20),
        ),
    ]
