# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20190730_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['-bug_upvotes']},
        ),
    ]
